server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user-service/**,/user-service
      - id: catalog-service
        uri: lb://CATALOG-SERVICE
        predicates:
          - Path=/catalog-service/**,/catalog-service
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/order-service/**,/order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


--- # Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:    # Gateway 전용 actuator 설정 추가
      enabled: true
