spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # 서버 자신을 Eureka 서버로 등록하지 않음
    fetch-registry: false # 서버 자신을 Eureka 서버로 등록하지 않음
